Set directory
This is used to save within the repo
All paths can be changed accordingly
```{r Set directory}
rm(list=ls())
dir <- "/Users/spyros/Documents/Labwork/Projects/Biohub/NE_Lung/"
```

<!-- Load data with doublets still there -->
<!-- ```{r Load data} -->
<!-- data_adult <- read.table(paste(dir,"input/GC_table_adult_NE.tsv",sep="")) -->
<!-- meta_adult_new <- read.table(paste(dir,"input/Metadata_table_adult_NE.tsv",sep="")) -->
<!-- ``` -->

Load data with doublets REMOVED
```{r Load data}
data_adult <- read.table(paste(dir,"input/secondary_input/GC_table_adult_NE_renamed_ND.tsv",sep=""))
meta_adult_new <- read.table(paste(dir,"input/secondary_input/Metadata_table_adult_NE_renamed_ND.tsv",sep=""))
```

Load additional datasets 
```{r Load additional data}
data.1 <- read.table(paste(dir,"input/external_datasets/Ahmad-counts.tsv",sep=""), sep=",", header = T, row.names = 1)
meta.1 <- as.data.frame(matrix(nrow=ncol(data.1),ncol=1))
meta.1$V1 <- "ahmad"
colnames(meta.1) <- "dataset"
row.names(meta.1) <- colnames(data.1)
# 
data.2 <- read.table(paste(dir,"input/external_datasets/Kyle-counts.tsv",sep=""), sep=",", header = T, row.names = 1)
meta.2 <- as.data.frame(matrix(nrow=ncol(data.2),ncol=1))
meta.2$V1 <- "kyle"
colnames(meta.2) <- "dataset"
row.names(meta.2) <- colnames(data.2)
#
data.3 <- read.table(paste(dir,"input/external_datasets/Lung-counts.tsv",sep=""), sep=",", header = T, row.names = 1)
meta.3 <- as.data.frame(matrix(nrow=ncol(data.3),ncol=1))
meta.3$V1 <- "tabula"
colnames(meta.3) <- "dataset"
row.names(meta.3) <- colnames(data.3)
# Combine all 
temp.1 <- merge(data.1, data.2, by=0)
row.names(temp.1) <- temp.1$Row.names
temp.1 <- temp.1[,-grep("Row.names", colnames(temp.1))]
data.all <- merge(temp.1,data.3,by=0)
row.names(data.all) <- data.all$Row.names
data.all <- data.all[,-grep("Row.names", colnames(data.all))]
meta.all <- rbind(meta.1,meta.2,meta.3)
# Plot 
boxplot(colSums(data.all)~meta.all$dataset)
```


```{r make metadata compatible}
meta.temp <- as.data.frame(matrix(nrow=ncol(data_adult),ncol=1))
meta.temp$V1 <- "NE"
colnames(meta.temp) <- "dataset"
row.names(meta.temp) <- colnames(data_adult)
```

```{r Combine all}
data.temp <- merge(data.all, data_adult, by = 0)
row.names(data.temp) <- data.temp$Row.names
data.temp <- data.temp[,-grep("Row.names",colnames(data.temp))]
meta.temp <- rbind(meta.all, meta.temp)
```

```{r Write tables}
write.table(data.temp, paste(dir,"input/secondary_input/GC_table_ALL_datasets_renamed_ND.tsv",sep=""))
write.table(meta.temp, paste(dir,"input/secondary_input/Metadata_ALL_datasets_renamed_ND.tsv",sep=""))
```